### ISSUE TITLE
Feedback: First Challenge Submission

### ISSUE THREAD

**Issue by anselb** [woodward4422/CS1.3_Data_Structures_Algorithms#1]
- I think you forgot to change a small thing in your decode function. I recommend running the tests again, and you'll probably find it.
- Nice doc strings in search.py; I appreciate that you've taken the time to do them as this is probably the last thing people will do in their code, but it will definitely help someone who looks at it for the first time.
- I would've liked to see more comments and/or spacing in your contains_and_first_index function as there appears to be a lot going on, and it is harder to read.

**Comment by woodward4422** [comment]
Thank you for the feedback, everything is updated to reflect the changes you suggested!
