### ISSUE TITLE
Feedback: Second Challenge Submission

### ISSUE THREAD

**Issue by anselb** [woodward4422/CS1.3_Data_Structures_Algorithms#2]
- Nice work on you stack and queue classes. Everything seems correct except for forgetting to return pop in ArrayStack pop, and the analysis for ArrayQueue enqueue seems to be mismatched.
- In your Sets class, everything seems to be correct there, but I think you mixed up union and intersection. You complexity annotations have some good depth there.
- Your set tests are fine the way they currently are, but you might consider varying the input to use strings as well. I would also like to see more testing of the size property.

**Comment by woodward4422** [comment]
I implemented all your suggested changes. Sorry for the confusion with the mixup with Union and Intersection, I got those mixed up initially by accident. I added some more tests with strings. Thank you!
